name: Manage CI Branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  manage-ci:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'ci'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    steps:
      - name: Delete old ci branch
        run: |
          gh pr list --state closed --head ci --json headRefName --jq '.[0].headRefName'
          gh branch delete ci

      - name: Create new ci branch from main
        run: |
          gh branch create ci